export const CREAR_SUB_EXITO = "CREAR_SUB_EXITO";
export const CREAR_SUB_FALLO = "CREAR_SUB_FALLO";

export const OBTENER_SUB_ADMIN = "OBTENER_SUB_ADMIN";
export const OBTENER_SUB = "OBTENER_SUB";

export const ELIMINAR_SUB_PREGUNTA = "ELIMINAR_SUB_PREGUNTA";
export const ELIMINAR_SUB_CANCELAR = "ELIMINAR_SUB_CANCELAR";
export const ELIMINAR_SUB_BORRAR = "ELIMINAR_SUB_BORRAR";

export const EDITAR_SUB_PREGUNTA = "EDITAR_SUB_PREGUNTA";
export const EDITAR_SUB_CANCELAR = "EDITAR_SUB_CANCELAR";
export const EDITAR_SUB_EDITAR = "EDITAR_SUB_EDITAR";