export const OBTENER_PEDIDOS_ADMIN = "OBTENER_PEDIDOS_ADMIN";
export const OBTENER_PEDIDOS = "OBTENER_PEDIDOS";
export const CARGAR_SPINNER = "CARGAR_SPINNER";
export const QUITAR_SPINNER = "QUITAR_SPINNER";