export const CREAR_USUARIO_EXITO = "CREAR_USUARIO_EXITO";
export const CREAR_USUARIO_FALLO = "CREAR_USUARIO_FALLO";

export const LOGIN_EXITO = "LOGIN_EXITO";
export const LOGIN_FALLO = "LOGIN_FALLO";

export const RECORDAR_USUARIO_EXITO = "RECORDAR_USUARIO_EXITO";
export const RECORDAR_USUARIO_FALLO = "RECORDAR_USUARIO_FALLO";

export const CAMBIAR_DATOS_PERSONALES_EXITO = "CAMBIAR_DATOS_PERSONALES_EXITO";
export const CAMBIAR_DATOS_PERSONALES_FALLO = "CAMBIAR_DATOS_PERSONALES_FALLO";

export const CAMBIAR_CONTRASEÑA_EXITO = "CAMBIAR_CONTRASEÑA_EXITO";
export const CAMBIAR_CONTRASEÑA_FALLO = "CAMBIAR_CONTRASEÑA_FALLO";

export const SALIR_CUENTA = "SALIR_CUENTA";

export const COMENZAR_BUSQUEDA = "COMENZAR_BUSQUEDA";

export const AGREGAR_CARRITO = "AGREGAR_CARRITO";
export const CAMBIAR_ENVIO = "CAMBIAR_ENVIO";
export const CALCULAR_TOTAL = "CALCULAR_TOTAL";

export const CARGAR_SPINNER = "CARGAR_SPINNER";
export const QUITAR_SPINNER = "QUITAR_SPINNER";