export const CREAR_PRODUCTO_EXITO = "CREAR_PRODUCTO_EXITO";
export const CREAR_PRODUCTO_FALLO = "CREAR_PRODUCTO_FALLO";

export const OBTENER_PRODUCTOS_ADMIN = "OBTENER_PRODUCTOS_ADMIN";
export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";

export const AGREGAR_PROMOCION_PREGUNTA = "AGREGAR_PROMOCION_PREGUNTA";
export const AGREGAR_PROMOCION_CANCELAR = "AGREGAR_PROMOCION_CANCELAR";
export const AGREGAR_PROMOCION_AGREGAR = "AGREGAR_PROMOCION_AGREGAR";

export const ELIMINAR_PRODUCTO_PREGUNTA = "ELIMINAR_PRODUCTO_PREGUNTA";
export const ELIMINAR_PRODUCTO_CANCELAR = "ELIMINAR_PRODUCTO_CANCELAR";
export const ELIMINAR_PRODUCTO_BORRAR = "ELIMINAR_PRODUCTO_BORRAR";

export const EDITAR_PRODUCTO_PREGUNTA = "EDITAR_PRODUCTO_PREGUNTA";
export const EDITAR_PRODUCTO_CANCELAR = "EDITAR_PRODUCTO_CANCELAR";
export const EDITAR_PRODUCTO_EDITAR = "EDITAR_PRODUCTO_EDITAR";

export const OBTENER_PRODUCTO = "OBTENER_PRODUCTO";
export const CARGANDO = "CARGANDO";
export const CARGANDO_COMPLETO = "CARGANDO_COMPLETO";